### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by youfoundron** [arddluma/awesome-list-testnet-faucets#11]
Great list! Will be add a few of these to my site - [cryptofaucet.dev](https://cryptofaucet.dev)

Just wated to say thank you!
Feel free to close 😃

**Comment by arddluma** [comment]
wow!!! 
this is so cool, very well organized and nice design!
Good job 🙏 
Thank you too for BUIDL-ing this!
I will add your website to this repo!
